### ISSUE TITLE
Undefined index: alf in C:\wamp\www\php-alf\Alfresco_CMIS_API.php on line 335

### ISSUE THREAD

**Issue by tharun777** [fvettore/php-alf-cmis-api#3]
Undefined index: alf in C:\wamp\www\php-alf\Alfresco_CMIS_API.php on line 335

please suggest me how to  solve it,
also if you attached any link of tutorial to follow steps even with examples it would be really helpful for new bee like me :)

**Comment by cifarellispa** [comment]
In the examples folder you will find some very basic examples. They are nearly a step by step tutorial :)

Your warning (or error?) means the ALF namespace is missing in XML reply. I cannot understand the reason without further info (alfresco version? what were you doing exactly?).

**Comment by tharun777** [comment]
Okay, When shall i expect the same, am awaiting :) also if you upload a video like in youtube tutorial along with tutorial it will really helpfull.

**Comment by tharun777** [comment]
Am trying to create some basic project with PHP and alfresco like DMS dashboard in php of alfresco CMIS repository.

**Comment by tharun777** [comment]
Hi, 
Can u please add any tutorial like a youtube video link, like your package is developed and  documented, so that i can get basic level of knowlegde and i can also try to contribute some code like CMS using php for interact with alfresco.

**Comment by tharun777** [comment]
Hi,

Any update on above ?,
I tried to upload a single file using this api to alfresco it was happening, but i need more clarity on what am doing. Please guide me the steps. How to utilize this package ?

Regards,
Tharun Kumar A

**Comment by tharun777** [comment]
I Will help you in enhance this package to some level. Am eager to dive into this package :)

**Comment by fvettore** [comment]
Dear tharun,
first of all thank you for your appreciation!
But we are not developing for money so we have no time to spend in creating youtube tutorials :)
From my point of view you can find the step by step you are asking for in the examples: every single situation is explained and commented inline. 
I think examples are clear enough and as you seems to confim, it is easy to use to upload a file and perform simple actions.

As clearly explained in the README this package was created with a goal and we ( my company and I) decided to share its since:
1) it is very simple
2) works fine in most situations

We use it every days and made little adjustments to improve it. The next step will be to make it compatible with Alfresco 5.x.

If you wish to help us to improve you are welcome.

Please note it has some limitations due to CMIS.
This is the reason why I developed a RESTful interface to perform other actions (user and groups management and so on)

**Comment by tharun777** [comment]
Dear Fabrizio Vettore,

Thank you for your kind reply for my post,
Am trying to do some CMS kind of application using core PHP which interact
with Alfresco to do basic functionality(CRUD).

Am not even able to make out how we are connecting to Alfresco using the
connect() function. If possible, can you please create a blog which would
be really helpful for persons like me. Just how this package was developed.

I will try to pickup from that blog and develop my custom CMS.  Also will
share the same.

Thanks in advance.

Regards,
Tharun Kumar A

**Comment by Mirdrack** [comment]
First of all, let me thank to @fvettore I really appreciate your effort doing this...  
And @tharun777 Iḿ at the same boat, I want to integrate this library to my system.  
I think you are not being able to connect because the maybe you are using Alfresco 5 version and this version returns the results on JSON and that breaks the library, I'm open to all ideas in order to solve this and migrate the library to version 5, hope @fvettore can help us.

Thnks and regards

**Comment by fvettore** [comment]
Added basic Alfresco5 compatibility. Not fully tested, but it seems to be working fine.
I am going to test it into production soon

**Comment by tharun777** [comment]
Cool... finally we got a pack which will run in Version 5 too :)

**Comment by fvettore** [comment]
Now compatible with 5.x. Closed
